spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_green_farm
        username: root
        password: root


debug: true

test:
    app: test
    name: yangzhijiang

alibaba:




