spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_admin
        username: root
        password: root

#logging:
#  config: classpath:log4j.xml.bak
#    level: debug
##    file: my.log
#    path: ./logs/
#debug: false

test:
    app: test
    name: yangzhijiang

